PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('health-and-beauty', 2, 'Skincare Products: Nourish and Protect', '["Healthy skin is the foundation of beautiful makeup. Rouge Technologies offers an extensive range of skincare products that hydrate, protect, and rejuvenate your skin. From moisturisers and serums to cleansers and sunscreens, each product is designed to address specific concerns such as dryness, sensitivity, or premature aging. Using high-quality skincare products ensures your skin stays smooth, radiant, and resilient, providing the perfect canvas for applying makeup.","Incorporating skincare products into your daily routine improves overall skin health and enhances the longevity and appearance of makeup. Each item is carefully selected for its effectiveness, safety, and suitability for modern skincare routines."]', unixepoch(), unixepoch()),
('health-and-beauty', 3, 'Womens Makeup: Tailored for Every Style', '["Our womens makeup range offers products specifically curated to meet the diverse needs of women, helping you achieve professional-level results from the comfort of your home. From eye makeup palettes to lip and cheek products, each item is formulated to deliver precise colour, easy blending, and long-lasting wear. These womens makeup products allow you to explore different styles, from natural and understated looks to bold, dramatic statements.","With high-quality womens makeup, you can confidently create versatile looks that suit any occasion. Whether for work, social events, or personal expression, our products are designed to make your makeup routine effortless, enjoyable, and professional in appearance.","Explore Rouge Technologies'' collection of makeup products, skincare products, and womens makeup to enhance your beauty routine, maintain healthy skin, and express your unique style with confidence and quality you can trust."]', unixepoch(), unixepoch()),
('musical-instruments-dj-equipment', 0, NULL, '["Enhance your music experience with a wide selection of wireless speakers, musical instruments, and noise cancelling headphones at Rouge Technologies. Whether you are a professional musician, a DJ, or an enthusiast, our collection is designed to provide high-quality audio, reliable performance, and the tools you need to create, perform, and enjoy music in any environment."]', unixepoch(), unixepoch()),
('musical-instruments-dj-equipment', 1, 'Wireless Speakers: Superior Sound Anywhere', '["Our range of wireless speakers delivers powerful, clear, and immersive sound for every occasion. Perfect for home studios, live performances, or casual listening, these speakers allow you to enjoy high-quality audio without the clutter of cables. Easy to connect via Bluetooth or Wi-Fi, our wireless speakers offer portability, convenience, and long battery life, making it simple to bring your music wherever you go.","Whether you are streaming tracks, DJing at a party, or simply enjoying your favourite playlists, our wireless speakers ensure that every note is crisp, balanced, and true to the artist''s intent. Durable construction and modern design make them a versatile choice for any music lover or professional setup."]', unixepoch(), unixepoch()),
('musical-instruments-dj-equipment', 2, 'Musical Instruments: Express Your Creativity', '["Rouge Technologies provides a comprehensive selection of musical instruments for beginners and professionals alike. From keyboards, guitars, and drums to electronic instruments and DJ controllers, each product is chosen for its quality, performance, and ease of use. Our musical instruments allow you to explore your creativity, develop your skills, and perform with confidence, whether in a studio, classroom, or on stage.","High-quality musical instruments offer superior sound, precise control, and durability, ensuring that your investment supports your musical journey for years to come. Whether you are composing, practicing, or performing live, our instruments provide the reliability and versatility needed to achieve professional results."]', unixepoch(), unixepoch());

-- Chunk 31 complete
