PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('smart-watches', 0, NULL, '["Enhance your lifestyle and stay connected with the latest smart watches at Rouge Technologies. Whether you are looking for a smart watch for women, a mens smart watch, or advanced fitness watches, our range offers stylish, functional, and reliable devices designed to meet your needs. From everyday notifications to health tracking and fitness monitoring, our smart watches combine modern technology with convenience and style."]', unixepoch(), unixepoch()),
('smart-watches', 1, 'Smart Watch for Women: Style Meets Functionality', '["Our smart watch for women selection combines elegant design with advanced features. These devices provide notifications, activity tracking, and connectivity while complementing your personal style. Whether you are managing your day, monitoring your health, or staying connected with calls and messages, a smart watch for women delivers performance and sophistication in one compact device.","Featuring heart rate monitoring, step counting, sleep tracking, and mobile notifications, these smart watches allow you to manage your health and productivity effortlessly. With intuitive interfaces and customizable watch faces, the smart watch for women is designed to enhance daily routines while maintaining a fashionable look."]', unixepoch(), unixepoch()),
('smart-watches', 2, 'Mens Smart Watch: Power and Precision', '["The mens smart watch combines rugged design with high-performance functionality. Ideal for professionals, athletes, and tech enthusiasts, these smart watches provide advanced tracking, seamless smartphone integration, and durable construction. With features such as GPS, heart rate monitoring, notifications, and fitness tracking, a mens smart watch ensures you remain organized, connected, and active throughout your day.","Mens smart watches are built for versatility, offering both casual and formal styles that suit every occasion. By choosing a mens smart watch, you gain access to a device that enhances productivity, supports fitness goals, and keeps you informed without the need to constantly check your phone."]', unixepoch(), unixepoch()),
('smart-watches', 3, 'Fitness Watches: Track, Train, and Improve', '["Fitness watches are essential for anyone focused on health and performance. Rouge Technologies offers fitness watches that monitor activity levels, heart rate, sleep quality, and calorie burn. These devices provide detailed insights into your training and recovery, helping you optimize workouts and achieve fitness goals effectively.","Designed with durability, water resistance, and intuitive interfaces, fitness watches make it easy to stay active and motivated. With features such as GPS tracking, guided workouts, and health monitoring, fitness watches are perfect for casual exercisers, professional athletes, or anyone seeking a more active lifestyle.","Whether you are searching for a smart watch for women, a mens smart watch, or dedicated fitness watches, Rouge Technologies provides a selection of high-quality devices to keep you connected, healthy, and stylish. Each smart watch combines cutting-edge technology with convenience, ensuring you enjoy a seamless and engaging experience every day."]', unixepoch(), unixepoch()),
('chargers', 0, NULL, '["Keeping your devices powered is essential for staying connected and productive, and Rouge Technologies offers a wide range of chargers to meet every need. Whether you want to buy iPhone chargers, buy laptop chargers, or buy portable chargers, our selection ensures reliable performance, durability, and convenience. From everyday charging to on-the-go solutions, our chargers are designed to keep your devices ready whenever you need them."]', unixepoch(), unixepoch());

-- Chunk 13 complete
