PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('smart-home', 1, 'Home Smart Devices for Everyday Convenience', '["Home smart devices simplify daily routines by allowing you to control lighting, climate, entertainment, and security systems with ease. From smart bulbs and thermostats to automated locks and cameras, these devices enhance your home environment and offer intuitive control through apps or voice commands. Using home smart devices can streamline everyday tasks, save energy, and ensure your home operates efficiently, even when you are away.","Investing in high-quality home smart devices ensures reliable performance and compatibility across various platforms. Whether you want to automate simple tasks or create a fully integrated smart home system, these devices offer flexibility and convenience, making your living space more functional and enjoyable."]', unixepoch(), unixepoch()),
('smart-home', 2, 'Smart Home Devices for Security and Efficiency', '["Smart home devices play a critical role in enhancing safety and optimizing home management. Security cameras, smart locks, and motion sensors allow you to monitor and protect your home in real time. Meanwhile, smart plugs, energy monitors, and connected appliances enable efficient energy usage, reducing utility costs and environmental impact. Incorporating these devices creates a secure, energy-conscious, and responsive living environment.","Rouge Technologies provides smart home devices that are easy to set up, user-friendly, and compatible with popular home automation platforms. These devices allow homeowners to control, schedule, and monitor multiple systems from a single interface, improving both security and convenience without sacrificing comfort or style."]', unixepoch(), unixepoch()),
('smart-home', 3, 'Smart Home Automation Devices for Seamless Integration', '["Smart home automation devices allow for complete control and customization of your connected home. By linking lighting, climate control, entertainment systems, and security devices, automation devices enable intelligent routines and synchronized operations. For example, you can program lights to adjust based on the time of day or trigger heating and cooling systems when entering or leaving a room. This level of automation enhances convenience, reduces energy waste, and provides a more comfortable home environment.","Rouge Technologies offers a wide range of smart home automation devices designed for reliability and scalability. Whether you are just starting your smart home journey or expanding an existing system, these devices provide the flexibility to integrate new technology seamlessly. Investing in smart home automation devices ensures your home remains connected, efficient, and responsive, creating a smarter, safer, and more enjoyable living space for you and your family."]', unixepoch(), unixepoch()),
('home-automation', 0, NULL, '["Transforming your living space into a modern, connected home is easy with the right smart home automation devices. Whether you are enhancing convenience, boosting security, or improving energy efficiency, Rouge Technologies offers a wide selection of smart home gadgets and smart home products designed to make your life simpler and more enjoyable. These devices allow seamless control of your home environment, providing comfort, safety, and efficiency all in one."]', unixepoch(), unixepoch()),
('home-automation', 1, 'Smart Home Automation Devices for Seamless Control', '["Smart home automation devices enable you to manage multiple systems within your home from a single interface. From automated lighting and climate control to smart security systems, these devices allow you to create schedules, set triggers, and automate tasks to fit your lifestyle. By integrating smart home automation devices, you can ensure your home operates smoothly and efficiently, whether you are present or away. These devices not only provide convenience but also optimize energy usage and reduce household costs.","Rouge Technologies'' smart home automation devices are compatible with popular platforms and offer intuitive setup and management. By connecting your smart lighting, thermostats, and appliances, you can build routines that adjust your home environment automatically, enhancing comfort, safety, and efficiency throughout the day."]', unixepoch(), unixepoch());

-- Chunk 6 complete
