PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('musical-instruments-dj-equipment', 3, 'Noise Cancelling Headphones: Focus and Clarity', '["For musicians, producers, and DJs, noise cancelling headphones are an essential tool for concentration and precision. Rouge Technologies offers a range of noise cancelling headphones that block unwanted background sounds while delivering crystal-clear audio. Ideal for studio work, live monitoring, or personal listening, these headphones provide comfort, accurate sound reproduction, and advanced noise reduction technology.","Whether you are mixing tracks, practicing instruments, or enjoying music privately, our noise cancelling headphones ensure that you can focus on every detail with clarity and comfort. Ergonomic design and long-lasting performance make them perfect for extended use, whether at home, in the studio, or on the go.","Explore Rouge Technologies'' collection of wireless speakers, musical instruments, and noise cancelling headphones to elevate your music creation, performance, and listening experience with professional-grade equipment and exceptional quality."]', unixepoch(), unixepoch()),
('in-car-tech', 0, NULL, '["Upgrade your driving experience with advanced in-car technology including sat nav, dash cams, and Apple CarPlay available at Rouge Technologies. Our collection is designed to enhance safety, convenience, and entertainment on the road, making every journey smoother and more enjoyable. Whether for daily commuting, road trips, or professional use, our in-car tech products combine innovation with reliability."]', unixepoch(), unixepoch()),
('in-car-tech', 1, 'Sat Nav: Navigate with Confidence', '["Our sat nav systems provide accurate, real-time navigation to help you reach your destination efficiently. Equipped with intuitive interfaces, clear directions, and up-to-date mapping, these devices reduce stress while driving and ensure you never get lost. From city streets to country roads, our sat nav products offer route optimisation, traffic updates, and easy integration with mobile devices, making your journeys safer and more predictable.","Whether you''re commuting to work, heading out on a road trip, or exploring new locations, a high-quality sat nav enhances your driving experience by providing reliable navigation, helpful alerts, and easy-to-read displays that keep your focus on the road."]', unixepoch(), unixepoch()),
('in-car-tech', 2, 'Dash Cams: Protect Your Vehicle and Journey', '["Dash cams are essential for documenting your journeys and providing security while on the road. Our selection of dash cams records high-definition video, capturing every moment of your drive. Whether for insurance purposes, monitoring parked vehicles, or ensuring road safety, dash cams offer peace of mind and reliable evidence in the event of incidents. Many models also include features such as night vision, motion detection, and GPS logging for comprehensive protection.","Installing a dash cam enhances vehicle security and helps you maintain accountability while driving. Easy to install and user-friendly, these dash cams ensure that every journey is recorded with clarity and precision, offering protection and reassurance for drivers and passengers alike."]', unixepoch(), unixepoch()),
('in-car-tech', 3, 'Apple CarPlay: Seamless Connectivity on the Move', '["Apple CarPlay allows you to integrate your iPhone seamlessly with your vehicle, providing hands-free access to maps, calls, messages, music, and apps. This technology enhances convenience and safety by allowing drivers to control essential functions via voice commands or the vehicle''s display. With Apple CarPlay, you can stay connected while keeping your focus on the road, ensuring a smarter and safer driving experience.","Whether navigating unfamiliar routes, streaming music, or communicating safely while driving, Apple CarPlay enhances your in-car experience. Compatible with a wide range of vehicles, this technology ensures that your iPhone becomes an intuitive extension of your dashboard, making every drive both enjoyable and efficient.","Explore Rouge Technologies'' range of sat nav, dash cams, and Apple CarPlay products to enhance safety, connectivity, and convenience on every journey. Our in-car tech solutions combine modern functionality with reliable performance, helping you drive with confidence and peace of mind."]', unixepoch(), unixepoch());

-- Chunk 32 complete
