PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('audio-visual', 3, 'Audio Visual Equipment: Enhance Your Entertainment Setup', '["High-quality audio visual equipment is essential for creating an immersive home or professional entertainment experience. From home cinema systems to professional-grade AV setups, Rouge Technologies offers equipment that delivers stunning sound and picture quality. By investing in the right audio visual equipment, you can elevate movies, music, and gaming sessions to new levels of enjoyment.","Our selection includes amplifiers, soundbars, projectors, and AV accessories that complement your wireless headphones and Bluetooth speakers. Carefully chosen for performance, durability, and ease of use, these products allow you to design a complete audio visual setup that meets your exact requirements.","Whether you are purchasing wireless headphones, a Bluetooth speaker, or full audio visual equipment, Rouge Technologies provides high-quality, reliable solutions to enhance your listening and viewing experiences. Each product is designed to deliver superior performance, convenience, and long-lasting enjoyment, making it simple to create an exceptional audio visual environment wherever you are."]', unixepoch(), unixepoch()),
('headphones', 0, NULL, '["Experience superior sound quality and comfort with our extensive range of headphones at Rouge Technologies. Whether you are looking for wireless headphones, noise cancelling headphones, or wireless earbuds, our collection is designed to provide exceptional audio performance, convenience, and style. Each product enhances your listening experience, whether for work, travel, or leisure."]', unixepoch(), unixepoch()),
('headphones', 1, 'Wireless Headphones: Freedom and Exceptional Sound', '["Wireless headphones offer the perfect combination of mobility, comfort, and high-quality sound. Our wireless headphones are ideal for music enthusiasts, commuters, and professionals who want clear audio without the hassle of cords. With long battery life, ergonomic designs, and advanced Bluetooth connectivity, these headphones let you enjoy your favorite music, podcasts, and calls seamlessly wherever you go.","Designed for both casual listeners and audiophiles, wireless headphones provide rich sound, deep bass, and crisp highs. Whether you are relaxing at home, working out, or traveling, they deliver a reliable and immersive audio experience."]', unixepoch(), unixepoch()),
('headphones', 2, 'Noise Cancelling Headphones: Focus and Immersion', '["Noise cancelling headphones are essential for anyone seeking to block out distractions and focus on what matters most. Rouge Technologies offers a range of noise cancelling headphones that use advanced technology to reduce ambient noise, making them ideal for travel, office work, or simply enjoying music without interruption. These headphones combine comfort, premium audio, and effective noise reduction to enhance concentration and listening pleasure.","With adjustable noise cancellation settings, superior sound quality, and comfortable ear cushions, our noise cancelling headphones allow you to enjoy music, podcasts, and calls in peace, no matter the environment."]', unixepoch(), unixepoch()),
('headphones', 3, 'Wireless Earbuds: Compact and Convenient Audio', '["Wireless earbuds provide a compact and portable solution for high-quality sound on the move. Rouge Technologies'' wireless earbuds offer crystal-clear audio, hands-free calls, and long-lasting battery life, making them perfect for commuting, workouts, and casual listening. With secure fits and intuitive touch controls, these earbuds deliver convenience and performance in a small, stylish package.","Whether you need earbuds for exercise, travel, or everyday use, our wireless earbuds combine excellent sound, comfort, and durability. They pair seamlessly with smartphones, tablets, and other Bluetooth-enabled devices to provide a reliable, enjoyable listening experience anywhere.","From wireless headphones and noise cancelling headphones to wireless earbuds, Rouge Technologies offers high-quality solutions to enhance your audio experience. Each product is carefully designed to deliver superior performance, comfort, and reliability, ensuring that your listening experience is immersive, convenient, and enjoyable every day."]', unixepoch(), unixepoch());

-- Chunk 16 complete
