PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('video-games', 0, NULL, '["Discover the latest and most exciting titles with Rouge Technologies'' extensive selection of video games. Whether you want to shop video games, visit our video games shop, or explore the best PS5 games, our collection ensures a diverse and immersive gaming experience for players of all ages and preferences. Each game is carefully curated to deliver quality, entertainment, and engaging gameplay."]', unixepoch(), unixepoch()),
('video-games', 1, 'Shop Video Games: Easy Access to Top Titles', '["Shopping video games has never been easier with Rouge Technologies. Our online and in-store options allow you to quickly find the latest releases, classic favourites, and critically acclaimed titles. From action-packed adventures to strategy games and family-friendly options, shopping video games with us provides a convenient way to build your gaming library with confidence.","Each game in our collection is sourced from trusted publishers, ensuring authenticity and compatibility with your preferred gaming platform. With clear descriptions, ratings, and reviews, shopping video games with Rouge Technologies helps you make informed choices that suit your play style and interests."]', unixepoch(), unixepoch()),
('video-games', 2, 'Video Games Shop: Your Gaming Destination', '["Our video games shop is designed to be a one-stop destination for all your gaming needs. Whether you are browsing for consoles, accessories, or standalone games, the video games shop provides an organised, easy-to-navigate environment. Knowledgeable staff and detailed online guides make it simple to find exactly what you are looking for, whether it''s a competitive multiplayer title or a relaxing single-player experience.","Visiting our video games shop also gives you access to exclusive offers, bundles, and pre-orders for upcoming releases. By combining a wide range of products with expert advice, our shop ensures a seamless and enjoyable shopping experience for both casual and dedicated gamers."]', unixepoch(), unixepoch()),
('video-games', 3, 'PS5 Games: Next-Generation Entertainment', '["PS5 games bring cutting-edge graphics, fast load times, and immersive gameplay to your fingertips. Rouge Technologies offers an extensive selection of PS5 games, including blockbuster titles, indie hits, and exclusive releases. Each game is optimised to take full advantage of the PlayStation 5 hardware, delivering stunning visuals, realistic physics, and engaging storylines.","Whether you are looking for thrilling adventures, competitive online play, or creative experiences, PS5 games provide endless entertainment possibilities. With detailed product information, compatibility checks, and customer support, Rouge Technologies makes it easy to find and enjoy the best PS5 games for your gaming setup.","From shopping video games and visiting our video games shop to exploring the latest PS5 games, Rouge Technologies offers everything needed to enhance your gaming collection. Each product is chosen for quality, authenticity, and performance, ensuring a superior and enjoyable gaming experience every time you play."]', unixepoch(), unixepoch()),
('consoles', 0, NULL, '["Upgrade your gaming setup with high-performance consoles from Rouge Technologies. Whether you are searching for a console for games, a versatile games console, or a top-quality video games console, our selection offers reliability, cutting-edge technology, and immersive entertainment. Each console is designed to deliver seamless gameplay and exceptional graphics, providing hours of enjoyment for gamers of all levels."]', unixepoch(), unixepoch());

-- Chunk 21 complete
