PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('wifi-routers-networking', 3, 'Wireless Routers for Seamless Networking', '["Wireless routers are key to creating a flexible and convenient home network. With no need for physical cabling, wireless routers offer the freedom to connect laptops, smartphones, tablets, smart TVs, and smart home devices with ease. Rouge Technologies'' wireless routers deliver high-speed connections, wide coverage, and reliability, ensuring that multiple devices can function simultaneously without interference or lag.","Rouge Technologies provides a range of wireless routers suitable for gaming, streaming, remote work, and smart home integration. Investing in high-quality wireless routers ensures a future-proof network capable of handling modern demands while maintaining consistent performance. Whether upgrading your existing setup or building a new network from scratch, our wireless routers provide the speed, reliability, and flexibility you need for a fully connected home."]', unixepoch(), unixepoch()),
('security', 0, NULL, '["Protecting your home and loved ones starts with reliable security solutions. Choosing the right security camera, home camera security system, and home alarm systems ensures that your property remains safe and monitored at all times. Rouge Technologies offers a wide range of high-quality security devices designed for peace of mind, whether you are at home or away."]', unixepoch(), unixepoch()),
('security', 1, 'Security Camera for Monitoring and Protection', '["A security camera is an essential tool for keeping your property safe. High-definition cameras allow you to monitor entrances, outdoor spaces, and interior areas in real time, providing a clear view of every movement. Modern security cameras come with motion detection, night vision, and smartphone alerts, ensuring that you are instantly notified of any unusual activity. By choosing a security camera from Rouge Technologies, you can maintain constant surveillance and act quickly to protect your home and belongings.","Rouge Technologies'' security cameras are designed to be easy to install and compatible with various smart devices. Whether you are monitoring a single room or an entire property, these cameras deliver reliable performance, high-quality imaging, and secure cloud or local storage options, making them an integral part of any home security strategy."]', unixepoch(), unixepoch()),
('security', 2, 'Home Camera Security for Comprehensive Coverage', '["Home camera security systems provide a complete view of your property, integrating multiple cameras to cover key areas. These systems are ideal for monitoring driveways, entry points, backyards, and interior spaces simultaneously. With features like remote access, automated alerts, and live streaming, home camera security ensures that you can keep an eye on your home from anywhere in the world.","Investing in a home camera security system from Rouge Technologies enhances both safety and convenience. Advanced functionality allows you to customize camera zones, schedule recordings, and integrate with other smart home devices for a connected security experience. This comprehensive approach gives homeowners confidence that every corner of their property is monitored and secure."]', unixepoch(), unixepoch()),
('security', 3, 'Home Alarm Systems for Added Protection', '["Home alarm systems provide an additional layer of security by detecting unauthorized entry, fire, or other emergencies. These systems can be integrated with security cameras and smart devices to create a cohesive safety network for your home. When a threat is detected, alarms are triggered, and notifications are sent to your smartphone, alerting you instantly and allowing for rapid response.","Rouge Technologies offers a variety of home alarm systems suitable for different property sizes and security needs. Whether you are protecting a small apartment or a large house, these systems are reliable, easy to install, and compatible with other smart security devices. By combining home alarm systems with security cameras and home camera security, you can create a fully monitored, safe, and responsive home environment.","Investing in high-quality security cameras, home camera security, and home alarm systems from Rouge Technologies ensures peace of mind, convenience, and reliable protection for your family and property. Each device is designed to deliver performance, durability, and advanced technology to safeguard your home effectively."]', unixepoch(), unixepoch());

-- Chunk 8 complete
