PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('business-office', 0, NULL, '["Equip your business with essential technology solutions, including card payment machines, business wifi routers, and security cameras. At Rouge Technologies, we provide high-quality products designed to improve efficiency, security, and connectivity in your office or commercial space. Whether you are running a small shop, a busy office, or a large enterprise, these tools help streamline operations and protect your business assets."]', unixepoch(), unixepoch()),
('business-office', 1, 'Card Payment Machines: Efficient Transactions', '["Our card payment machines make transactions fast, secure, and reliable. Designed for businesses of all sizes, these devices support a variety of payment methods, including contactless, chip, and mobile payments. By integrating a card payment machine into your business, you can provide a smooth checkout experience, reduce queues, and enhance customer satisfaction. Advanced features like receipt printing, reporting, and connectivity options ensure that managing payments is simple and efficient.","Whether you run a retail store, café, or professional service, investing in a high-quality card payment machine ensures your business can accept payments seamlessly, improving both workflow and customer convenience."]', unixepoch(), unixepoch()),
('business-office', 2, 'Business Wifi Routers: Reliable Connectivity', '["Business wifi routers are essential for maintaining strong and secure internet connections in office environments. Our range of business wifi routers provides fast, stable, and reliable connectivity for multiple users and devices. With features like guest networks, encryption, and network management tools, these routers ensure that your staff and customers can stay connected without interruptions.","From small offices to large corporate setups, business wifi routers from Rouge Technologies deliver consistent performance, enhanced security, and easy scalability. Strong wifi infrastructure supports productivity, smooth communication, and efficient operations across all departments, helping your business run without connectivity issues."]', unixepoch(), unixepoch()),
('business-office', 3, 'Security Cameras: Protect Your Business', '["Security cameras are a vital component of any business safety plan. Our high-quality security cameras provide clear surveillance, real-time monitoring, and advanced features such as motion detection and night vision. Installing security cameras allows you to monitor entrances, workspaces, and critical areas, ensuring both staff and assets are protected around the clock.","Whether for deterrence, incident documentation, or remote monitoring, security cameras offer peace of mind and help maintain a safe business environment. With options suitable for indoor and outdoor use, these cameras are designed to integrate seamlessly with your existing security systems.","Rouge Technologies offers a complete selection of card payment machines, business wifi routers, and security cameras to support efficient, connected, and secure business operations. Investing in these solutions ensures that your business is equipped for productivity, customer satisfaction, and long-term growth."]', unixepoch(), unixepoch()),
('miscellaneous-tech', 0, NULL, '["Discover a wide range of stylish and reliable timepieces with our selection of mens sport watches, womens analogue watches, and quartz watches. At Rouge Technologies, we focus on offering products that combine functionality, durability, and design, helping you keep track of time while complementing your personal style. Whether for sports, everyday wear, or professional settings, our watches are built to meet diverse needs."]', unixepoch(), unixepoch());

-- Chunk 33 complete
