PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('gaming-headsets', 3, 'Headset for Gaming: Precision and Comfort', '["A headset for gaming combines high-fidelity audio, ergonomic design, and reliable durability. Rouge Technologies offers headsets for gaming that are compatible with multiple platforms, including PC, consoles, and mobile devices. These headsets are ideal for competitive environments, providing enhanced spatial awareness and clear voice communication to give you an edge over opponents.","Features such as noise-cancelling microphones, surround sound, and customizable audio profiles ensure a personalized and immersive experience. A headset for gaming from Rouge Technologies is designed to handle long sessions while maintaining comfort, stability, and consistent performance, making it a vital tool for any gamer.","Whether you choose a gaming headset, a wireless gaming headset, or a headset for gaming, Rouge Technologies provides top-quality products designed to deliver exceptional sound, comfort, and reliability. Elevate your gaming setup and enjoy a fully immersive audio experience with our expertly selected headsets."]', unixepoch(), unixepoch()),
('other-gaming', 0, NULL, '["Upgrade your gaming setup with essential gaming accessories from Rouge Technologies. Whether you are looking for gaming accessories, game accessories, or want to buy gaming accessories, our range is designed to enhance your gameplay, improve control, and deliver a fully immersive experience. Each product combines quality, durability, and performance to help you get the most out of your gaming sessions."]', unixepoch(), unixepoch()),
('other-gaming', 1, 'Gaming Accessories: Enhance Every Play', '["Gaming accessories are key to taking your gameplay to the next level. Rouge Technologies offers a variety of gaming accessories including controllers, keyboards, mice, headsets, and more. These products are designed to provide precision, responsiveness, and ergonomic comfort, helping you perform better whether you are playing casual games or competing at a professional level.","With high-quality gaming accessories, players can enjoy smoother input, faster reactions, and a more immersive experience. Adjustable settings, programmable buttons, and customizable designs make gaming accessories ideal for tailoring your setup to your individual style and preferences."]', unixepoch(), unixepoch()),
('other-gaming', 2, 'Game Accessories: Essential Tools for Gamers', '["Game accessories include items that complement consoles, PCs, and mobile gaming devices. Rouge Technologies'' selection of game accessories ensures compatibility, durability, and enhanced functionality. From controller grips and cooling pads to storage solutions and protective gear, game accessories allow you to maintain your equipment, improve comfort, and optimise performance during long sessions.","Game accessories are not only practical but also designed to enhance your gaming environment. They provide better control, improve ergonomics, and add convenience, making them an essential addition for both casual and competitive gamers."]', unixepoch(), unixepoch()),
('other-gaming', 3, 'Buy Gaming Accessories: Convenient and Reliable', '["Buying gaming accessories from Rouge Technologies ensures you receive high-quality, reliable products that meet your gaming needs. Whether you are upgrading your current setup or starting a new gaming rig, our range of buy gaming accessories options allows you to find everything from essential peripherals to advanced tools for enhanced gameplay.","With fast shipping, expert support, and carefully curated products, purchasing gaming accessories is simple and convenient. Investing in the right gaming accessories can significantly improve your gaming experience, providing comfort, performance, and long-lasting durability for hours of immersive play.","From gaming accessories to game accessories and a complete range to buy gaming accessories, Rouge Technologies offers everything needed to create a top-tier gaming setup. Each product is chosen to enhance performance, comfort, and enjoyment for gamers of all levels."]', unixepoch(), unixepoch());

-- Chunk 24 complete
