PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('apple-iphone', 3, 'Shop iPhone: Convenient and Flexible Options', '["Shopping iPhone devices online at Rouge Technologies allows you to explore the full range of models from the comfort of your home. With user-friendly navigation, detailed product descriptions, and secure checkout, shopping iPhone devices has never been easier. You can compare specifications, features, and prices to select the device that best meets your needs.","Rouge Technologies offers fast delivery, trusted support, and warranty options, making it simple to shop iPhone devices with confidence. Whether you are looking for the latest iPhone release or a reliable earlier model, our online store provides a convenient way to access high-quality Apple smartphones and enjoy all the benefits of modern mobile technology.","From exploring iPhones for sale to buying the perfect device or shopping iPhone models online, Rouge Technologies ensures a premium experience. Each iPhone is designed to deliver performance, durability, and advanced functionality, keeping you connected, productive, and entertained in today''s fast-paced digital world."]', unixepoch(), unixepoch()),
('android-smart-phones', 0, NULL, '["Finding the perfect Android device has never been easier with Rouge Technologies. Whether you are searching for cheap Android phones, looking for a reliable Android mobile phone, or exploring the latest Android smartphone models, we provide a wide selection of devices designed to suit every budget and lifestyle. Our Android Smart Phones combine functionality, performance, and durability to keep you connected, productive, and entertained."]', unixepoch(), unixepoch()),
('android-smart-phones', 1, 'Cheap Android Phones for Every Budget', '["Rouge Technologies offers a range of cheap Android phones that deliver excellent performance without compromising on quality. These devices are perfect for users seeking affordability while still benefiting from modern smartphone features. From efficient processors and responsive touchscreens to long-lasting batteries and robust build quality, cheap Android phones from Rouge Technologies ensure a reliable experience for calls, messaging, browsing, and social media.","Whether you need a secondary device, a first smartphone, or a budget-friendly upgrade, our collection of cheap Android phones allows you to stay connected and productive without breaking the bank. Each device is carefully selected to provide value, reliability, and modern capabilities at an accessible price."]', unixepoch(), unixepoch()),
('android-smart-phones', 2, 'Android Mobile Phone: Performance and Versatility', '["An Android mobile phone offers a flexible, user-friendly experience for personal and professional use. At Rouge Technologies, our Android mobile phone range includes models with high-resolution displays, powerful processors, ample storage, and advanced cameras. These devices are ideal for multitasking, media consumption, productivity, and communication.","Choosing an Android mobile phone allows you to customize your device with apps, widgets, and settings to match your workflow and lifestyle. Whether you are streaming videos, participating in video calls, or managing tasks on the go, our Android mobile phones provide smooth performance and reliability to meet daily demands."]', unixepoch(), unixepoch()),
('android-smart-phones', 3, 'Android Smartphone: Advanced Features for Modern Living', '["For users seeking cutting-edge technology, our Android smartphone selection offers the latest innovations in mobile devices. From high-speed processors and AI-powered cameras to large, vibrant screens and robust connectivity options, Android smartphones from Rouge Technologies enhance every aspect of digital life. These devices integrate seamlessly with accessories, smart home systems, and cloud services, providing a fully connected experience.","Investing in an Android smartphone ensures access to the latest software updates, security features, and multimedia capabilities. Whether for work, entertainment, or social connectivity, our Android smartphones provide the tools needed to stay productive, organized, and engaged. Rouge Technologies offers a range of Android smartphone models to suit different preferences, from compact designs to flagship devices with premium features.","By choosing cheap Android phones, Android mobile phones, or the latest Android smartphones from Rouge Technologies, customers can enjoy reliable, high-performance devices that cater to all aspects of modern life. Each product is carefully curated to provide durability, convenience, and an exceptional user experience."]', unixepoch(), unixepoch());

-- Chunk 12 complete
