PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('other-sound-vision', 3, 'Cables and Accessories: Organise and Optimise Your Setup', '["Cables and accessories play a critical role in ensuring a smooth, reliable, and efficient home audio-visual experience. Rouge Technologies offers a comprehensive range of cables and accessories to connect, protect, and enhance your devices. From power cables and extension leads to adapters and cable management solutions, these products help you maintain a tidy and effective setup.","High-quality cables and accessories ensure signal stability, compatibility, and long-term reliability. Whether you are integrating a home theatre, connecting multiple devices, or managing complex AV systems, these essential components help you achieve optimal performance and a streamlined, user-friendly environment.","From audio accessories and cables to TV wall brackets and essential cables and accessories, Rouge Technologies provides everything you need to create a high-performing and organised audio-visual setup. Each product is carefully selected to deliver durability, convenience, and superior functionality, ensuring your home entertainment experience is immersive, efficient, and enjoyable."]', unixepoch(), unixepoch()),
('gaming', 0, NULL, '["Step into the world of immersive entertainment with premium gaming products from Rouge Technologies. Whether you are looking for gaming consoles, gaming controllers, or want to explore PC gaming, our range provides cutting-edge technology, reliability, and performance for every type of gamer. Each product is designed to elevate your gaming experience, whether at home or in a competitive setting."]', unixepoch(), unixepoch()),
('gaming', 1, 'Gaming Consoles: Ultimate Entertainment Systems', '["Gaming consoles offer a complete entertainment solution, combining high-quality graphics, intuitive controls, and a vast library of games. Rouge Technologies provides the latest gaming consoles from top brands, ensuring smooth gameplay, immersive visuals, and responsive performance. Whether you are playing solo, with friends, or online, gaming consoles provide hours of entertainment with seamless access to new releases and exclusive titles.","Modern gaming consoles also include multimedia features, allowing you to stream movies, music, and other content. With built-in connectivity options, online multiplayer capabilities, and sleek designs, gaming consoles are the heart of any home entertainment setup."]', unixepoch(), unixepoch()),
('gaming', 2, 'Gaming Controllers: Precision and Comfort', '["A gaming controller is essential for achieving precise control and an enhanced gaming experience. Rouge Technologies offers a wide range of gaming controllers designed for comfort, accuracy, and durability. Whether you are navigating complex game worlds, competing in fast-paced action, or enjoying casual gaming sessions, a high-quality gaming controller provides responsive feedback and ergonomic design to keep you playing longer without fatigue.","Compatible with multiple gaming consoles and PC setups, our gaming controllers allow you to experience your games as they were intended, with intuitive button layouts, adjustable sensitivity, and customisable features for advanced users."]', unixepoch(), unixepoch()),
('gaming', 3, 'PC Gaming: High-Performance for Serious Gamers', '["PC gaming offers unparalleled flexibility, performance, and visual fidelity. Rouge Technologies provides a comprehensive selection of PC gaming components, from high-end graphics cards and processors to complete gaming rigs ready for immersive gameplay. Whether you are exploring the latest AAA titles, competitive esports, or creative mods, PC gaming delivers the ultimate experience with smooth frame rates, stunning graphics, and advanced control options.","With the ability to upgrade individual components, PC gaming allows you to customise your setup to meet your exact performance needs. From VR compatibility to multi-monitor setups, PC gaming provides limitless possibilities for enhancing your play style and creating a truly personalised gaming environment.","From gaming consoles and gaming controllers to PC gaming, Rouge Technologies offers everything needed to create the perfect gaming setup. Each product is selected for performance, reliability, and enjoyment, ensuring that gamers of all levels can experience immersive, responsive, and high-quality entertainment every time they play."]', unixepoch(), unixepoch());

-- Chunk 20 complete
