PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('drones', 2, 'DJI Drones UK: Trusted Performance and Innovation', '["DJI drones UK are known for their cutting-edge technology and reliability. Rouge Technologies stocks a wide range of DJI drones, including models suited for beginners, enthusiasts, and professional users. These drones offer advanced features such as obstacle avoidance, GPS navigation, and intelligent shooting modes, allowing you to capture professional-quality footage with ease.","Choosing DJI drones UK ensures you receive a product that is engineered for performance, durability, and ease of use. With options ranging from compact models to professional-grade drones, you can find the perfect device to suit your photography or videography needs."]', unixepoch(), unixepoch()),
('drones', 3, 'Buy Drones UK: Convenient and Reliable', '["When you buy drones UK from Rouge Technologies, you can shop with confidence knowing that you are getting authentic, high-quality products. Our online store makes it easy to browse and purchase drones, accessories, and spare parts, providing everything you need for a complete aerial photography setup. Whether upgrading your current drone or purchasing your first device, buying drones UK is a straightforward and reliable experience.","Investing in a drone from Rouge Technologies ensures long-lasting performance, support, and access to cutting-edge technology. From drones with cameras to DJI drones UK, our selection is curated to provide enthusiasts and professionals with the tools needed to capture stunning aerial imagery with precision, creativity, and ease."]', unixepoch(), unixepoch()),
('camcorders', 0, NULL, '["Capture every moment in stunning clarity with a selection of camcorders from Rouge Technologies. Whether you are searching for a digital video camera, a digital video camcorder, or a 4K video camera, our range is designed to suit both beginners and professional videographers. Each device combines advanced imaging technology, ease of use, and reliable performance to ensure high-quality recordings every time."]', unixepoch(), unixepoch()),
('camcorders', 1, 'Digital Video Camera: Record Life in Detail', '["A digital video camera is ideal for everyday recording, capturing family events, travel memories, or creative projects with ease. Rouge Technologies offers a wide selection of digital video cameras that feature high-resolution sensors, optical zoom, and image stabilisation to produce smooth and sharp footage. These cameras are lightweight, portable, and easy to operate, making them perfect for those who want professional-quality results without complex setups.","From casual home videos to semi-professional projects, a digital video camera ensures every shot is vivid and precise. With intuitive controls and versatile recording options, users can focus on creativity while achieving high-quality video output."]', unixepoch(), unixepoch()),
('camcorders', 2, 'Digital Video Camcorder: Professional Features for Everyday Use', '["Digital video camcorders provide additional features and flexibility for more advanced filming needs. Rouge Technologies'' range of digital video camcorders includes models with high-definition recording, adjustable frame rates, and excellent low-light performance. These camcorders are perfect for documenting events, creating content for social media, or producing short films, providing users with professional-grade tools in a user-friendly format.","With features like built-in microphones, external audio support, and multiple shooting modes, a digital video camcorder allows for precise control over audio and visual quality. This makes it easier to create compelling videos that capture every detail with clarity and professionalism."]', unixepoch(), unixepoch());

-- Chunk 27 complete
