PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('diy', 0, NULL, '["Tackling home projects and repairs is easier with the right DIY products. Whether you are upgrading your kitchen, completing small repairs, or embarking on creative projects, having access to high-quality tools and equipment is essential. Rouge Technologies offers a wide selection of DIY products, tools and equipment, and kitchen and appliances to help you achieve professional results from the comfort of your own home."]', unixepoch(), unixepoch()),
('diy', 1, 'DIY Products for Every Home Project', '["Our range of DIY products covers a wide spectrum of home improvement needs, from painting and decorating to assembly and repairs. Durable and reliable, these products are designed to simplify tasks and ensure long-lasting results. Whether you are installing shelving, building furniture, or updating your living space, investing in quality DIY products allows you to work efficiently and safely while achieving excellent outcomes.","Rouge Technologies provides DIY products suitable for beginners and experienced enthusiasts alike. Each product is carefully selected to offer reliability, ease of use, and versatility, ensuring that every home project can be completed with confidence and precision."]', unixepoch(), unixepoch()),
('diy', 2, 'Tools and Equipment for Reliable Performance', '["Having the right tools and equipment is crucial for completing any DIY task successfully. From hand tools and power tools to measuring devices and safety gear, Rouge Technologies supplies a wide range of products to meet diverse project requirements. Quality tools and equipment not only make tasks easier but also increase safety, efficiency, and the overall quality of your work.","Our selection includes everything from drills, saws, and screwdrivers to specialized equipment for plumbing, electrical work, and carpentry. With tools and equipment from Rouge Technologies, you can tackle repairs, renovations, and home improvement projects with confidence, ensuring professional-level results every time."]', unixepoch(), unixepoch()),
('diy', 3, 'Kitchen and Appliances for Modern Homes', '["Upgrading your kitchen or appliances is an essential part of any DIY home project. Rouge Technologies offers kitchen and appliances that are functional, durable, and designed to complement modern living spaces. From small countertop appliances to essential kitchen tools, these products help make cooking, cleaning, and organizing more efficient and enjoyable.","Investing in quality kitchen and appliances ensures long-lasting performance and convenience. Whether you are installing new appliances, upgrading existing equipment, or adding helpful tools to your kitchen, Rouge Technologies provides reliable options that combine functionality, style, and innovation, allowing you to complete your projects with ease and confidence.","By choosing DIY products, tools and equipment, and kitchen and appliances from Rouge Technologies, homeowners and enthusiasts can confidently undertake projects with professional results. Each item is designed to provide durability, reliability, and ease of use, helping you enhance your home while saving time and effort."]', unixepoch(), unixepoch()),
('other-smart-home', 0, NULL, '["Creating a connected, convenient, and secure living environment is easier with the right smart home automation devices. Whether you are upgrading your home''s technology, improving energy efficiency, or enhancing security, Rouge Technologies offers a wide range of smart home gadgets and smart home products to suit every need. These devices help simplify daily routines, improve comfort, and provide full control over your home environment."]', unixepoch(), unixepoch());

-- Chunk 9 complete
