PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('other-mobile-phones-wearable-tech', 2, 'iPhone Accessories: Enhance Your Apple Device', '["Rouge Technologies offers a wide range of iPhone accessories to help you get the most out of your device. From protective cases and screen guards to docking stations and portable power solutions, our iPhone accessories ensure your smartphone remains functional, stylish, and secure. By using quality iPhone accessories, you can enhance device longevity, improve usability, and personalise your Apple experience.","Whether you are looking to protect your device from daily wear and tear, charge efficiently, or expand its functionality with smart add-ons, iPhone accessories from Rouge Technologies offer practical and innovative solutions. Each product is selected for compatibility, reliability, and durability."]', unixepoch(), unixepoch()),
('other-mobile-phones-wearable-tech', 3, 'USB C Charging Cable: Fast and Reliable Power', '["Maintaining power for your devices is essential, and a high-quality USB C charging cable ensures fast, safe, and efficient charging. Rouge Technologies'' USB C charging cables are compatible with a wide range of smartphones, tablets, laptops, and other electronics. These cables are designed to support rapid charging, data transfer, and long-term durability, providing a reliable solution for daily use.","Whether you need a USB C charging cable for your iPhone, Android device, or other USB-C enabled gadgets, our selection guarantees safety and performance. Sturdy construction, tangle-free designs, and universal compatibility make these cables a practical and essential addition to your mobile and wearable tech accessories.","From smart rings to iPhone accessories and USB C charging cables, Rouge Technologies offers a curated range of products that enhance usability, convenience, and connectivity. Each item is chosen to ensure high performance, durability, and a seamless user experience, helping you get the most from your mobile devices and wearable technology."]', unixepoch(), unixepoch()),
('audio-visual', 0, NULL, '["Immerse yourself in premium sound and entertainment with our range of audio and visual equipment at Rouge Technologies. Whether you are searching for wireless headphones, a Bluetooth speaker, or other audio visual equipment, our products are designed to deliver high-quality performance, convenience, and style. Each item enhances your listening and viewing experience, whether at home, on the go, or during professional use."]', unixepoch(), unixepoch()),
('audio-visual', 1, 'Wireless Headphones: Freedom and High-Quality Sound', '["Wireless headphones offer the ultimate combination of mobility, comfort, and exceptional sound quality. Rouge Technologies provides a wide selection of wireless headphones designed for music lovers, gamers, and professionals alike. With features such as noise cancellation, long battery life, and ergonomic designs, these headphones allow you to enjoy crisp audio without the restriction of cables.","Whether you are listening to music, taking calls, or watching videos, wireless headphones provide clear, immersive sound while keeping you free to move. They are ideal for commuting, working out, or relaxing at home, offering a seamless audio experience that combines practicality with style."]', unixepoch(), unixepoch()),
('audio-visual', 2, 'Bluetooth Speaker: Portable Sound for Every Occasion', '["Our Bluetooth speakers provide powerful, high-fidelity sound in a compact and portable format. Perfect for home entertainment, outdoor gatherings, or travel, these speakers connect easily to your smartphone, tablet, or laptop. Rouge Technologies'' Bluetooth speakers are designed for durability, long battery life, and superior audio clarity, ensuring your music, podcasts, and videos sound their best wherever you are.","With easy pairing, intuitive controls, and modern designs, a Bluetooth speaker enhances your audio experience while offering flexibility and convenience. Whether hosting a party, relaxing at home, or taking your music on the move, these speakers provide a reliable and enjoyable listening experience."]', unixepoch(), unixepoch());

-- Chunk 15 complete
