PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('pc-gaming', 2, 'Gaming Desktops: Maximum Performance', '["For gamers seeking the ultimate performance, gaming desktops offer unmatched power and flexibility. Rouge Technologies'' gaming desktops feature high-end CPUs, advanced graphics cards, and expandable memory options to handle the most demanding games and applications. Each system is built for stability, speed, and precision, ensuring an immersive experience whether you are engaging in competitive multiplayer matches or creative projects.","Gaming desktops also provide extensive upgrade potential, allowing users to enhance graphics, storage, and cooling over time. This makes them a long-term investment for serious gamers who want a system that evolves with the latest technology trends. From virtual reality support to multi-monitor setups, gaming desktops deliver the versatility and performance needed for a professional-level gaming setup."]', unixepoch(), unixepoch()),
('pc-gaming', 3, 'Gaming Monitors: Stunning Visuals and Responsiveness', '["Complement your gaming laptop or desktop with a high-quality gaming monitor. Rouge Technologies offers gaming monitors with fast refresh rates, low input lag, and vibrant color reproduction to bring every game to life. Whether you are playing fast-paced shooters, strategy games, or immersive RPGs, a gaming monitor enhances your experience with crisp visuals and smooth motion.","Many of our gaming monitors feature adaptive sync technologies, ergonomic stands, and multiple connectivity options, ensuring both comfort and compatibility with your existing setup. A premium gaming monitor not only improves performance but also provides an immersive viewing experience for movies, streaming, and creative tasks.","From gaming laptops and desktops to gaming monitors, Rouge Technologies offers everything needed for a complete PC gaming setup. Each product is selected for performance, reliability, and durability, helping gamers of all levels enjoy an engaging, responsive, and visually stunning gaming experience."]', unixepoch(), unixepoch()),
('gaming-headsets', 0, NULL, '["Enhance your gaming experience with premium gaming headsets from Rouge Technologies. Whether you are looking for a standard gaming headset, a wireless gaming headset, or a specialized headset for gaming, our range ensures crystal-clear audio, immersive sound, and comfortable designs. Each headset is engineered to provide high-quality sound, reliable performance, and durability for hours of gameplay."]', unixepoch(), unixepoch()),
('gaming-headsets', 1, 'Gaming Headset: Immersive Sound for Every Game', '["A gaming headset is essential for any serious gamer seeking precision and immersion. Rouge Technologies offers gaming headsets with rich audio, deep bass, and clear treble to ensure every sound effect and dialogue is perfectly reproduced. Whether playing fast-paced action games, strategic multiplayer titles, or story-driven adventures, a gaming headset provides the audio clarity and spatial awareness necessary for peak performance.","Designed with comfort in mind, gaming headsets feature adjustable headbands, cushioned ear cups, and lightweight construction to reduce fatigue during extended sessions. Integrated microphones offer clear communication with teammates, making it easier to coordinate strategies and enjoy online multiplayer experiences."]', unixepoch(), unixepoch()),
('gaming-headsets', 2, 'Wireless Gaming Headset: Freedom and Flexibility', '["A wireless gaming headset combines superior audio performance with freedom of movement. Rouge Technologies'' wireless gaming headsets deliver lag-free sound, long battery life, and stable connectivity, allowing you to focus on gameplay without being tethered by cables. Ideal for both casual and competitive gamers, these headsets offer flexibility without sacrificing sound quality or comfort.","With intuitive controls and customizable settings, a wireless gaming headset provides seamless adjustments for volume, surround sound, and microphone functions. Whether streaming, communicating with friends, or engaging in immersive gameplay, a wireless gaming headset ensures convenience, reliability, and exceptional performance."]', unixepoch(), unixepoch());

-- Chunk 23 complete
