PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('projectors', 1, 'Home Projector: Flexible and High-Quality Viewing', '["A home projector offers the versatility to enjoy movies, TV shows, and presentations on a larger screen from the comfort of your home. Rouge Technologies'' home projectors deliver sharp resolution, bright displays, and vibrant colours to create an immersive experience. Ideal for living rooms, bedrooms, or multi-purpose spaces, a home projector provides the flexibility to enjoy entertainment wherever you choose.","With easy connectivity options, including HDMI, USB, and wireless streaming, a home projector allows you to connect your devices effortlessly. Whether you are watching family movies, hosting a game night, or streaming online content, a home projector ensures a reliable and enjoyable viewing experience."]', unixepoch(), unixepoch()),
('projectors', 2, 'Home Cinema Projector: Create the Ultimate Movie Experience', '["A home cinema projector is perfect for those who want a true cinematic experience at home. Rouge Technologies'' home cinema projectors provide high-definition resolution, superior colour accuracy, and deep contrast levels, delivering visuals that rival commercial cinemas. With advanced projection technology, these projectors make every movie night, sports event, or gaming session unforgettable.","Designed for immersive viewing, home cinema projectors often include features such as adjustable keystone correction, zoom capabilities, and high-lumen output to ensure clear images even in larger rooms or with ambient light. By using a home cinema projector, you can enjoy big-screen entertainment without leaving your home."]', unixepoch(), unixepoch()),
('projectors', 3, 'Projector for Television: Expand Your Screen Options', '["A projector for television offers an alternative to traditional TV screens, providing a larger display and flexible placement options. Rouge Technologies'' projectors for television allow you to project content from your existing TV or streaming device onto a wall or screen, creating a more engaging viewing experience. These projectors are compatible with various devices, including smart TVs, set-top boxes, and gaming consoles.","With easy setup, adjustable display settings, and high-quality image output, a projector for television ensures an enhanced viewing experience for movies, sports, and gaming. It is an ideal solution for households seeking a bigger screen without compromising space or quality.","From home projectors and home cinema projectors to projectors for television, Rouge Technologies offers a curated range of products designed to provide exceptional visuals, convenience, and reliability. Each projector is built to deliver immersive entertainment, making it easy to enjoy cinematic experiences in the comfort of your own home."]', unixepoch(), unixepoch()),
('speakers', 0, NULL, '["Enhance your audio experience with high-quality speakers from Rouge Technologies. Whether you are searching for a Bluetooth speaker, portable speakers, or wireless speakers, our range offers superior sound, convenience, and durability. Each product is designed to deliver clear, powerful audio, whether at home, outdoors, or on the go."]', unixepoch(), unixepoch()),
('speakers', 1, 'Bluetooth Speaker: Effortless Wireless Connectivity', '["Bluetooth speakers allow you to enjoy music, podcasts, and calls without the hassle of wires. Rouge Technologies offers a variety of Bluetooth speakers that combine high-quality audio, sleek designs, and reliable connectivity. With long battery life, responsive controls, and robust sound performance, these speakers provide a convenient way to listen to your favourite content anywhere.","Whether you are hosting a small gathering, relaxing at home, or enjoying the outdoors, Bluetooth speakers offer flexibility and portability without compromising on sound quality. Pair them with your smartphone, tablet, or laptop for seamless wireless audio streaming."]', unixepoch(), unixepoch());

-- Chunk 18 complete
