PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('consoles', 1, 'Console for Games: Seamless Play and Performance', '["A console for games provides a complete gaming experience with intuitive controls, fast processing, and access to a wide library of titles. Rouge Technologies offers consoles for games that deliver smooth performance, responsive gameplay, and high-resolution graphics, ensuring you get the most out of every session. Whether you enjoy fast-paced action, strategy, or adventure games, these consoles are built to handle them all with ease.","With advanced connectivity features, these consoles allow you to play online multiplayer games, stream content, and access digital stores. A console for games from Rouge Technologies ensures reliability, durability, and maximum entertainment value for your home gaming setup."]', unixepoch(), unixepoch()),
('consoles', 2, 'Games Console: Designed for Every Gamer', '["Our games console collection caters to players seeking versatility and performance. Rouge Technologies provides a variety of games consoles suitable for casual players, families, and competitive gamers alike. Each games console features user-friendly interfaces, robust hardware, and a broad selection of compatible titles, making it easy to find the perfect fit for your gaming style.","Whether you are exploring new releases, replaying classic favourites, or engaging in online competitions, a games console enhances your gaming experience with immersive visuals, smooth frame rates, and reliable controls. Portability, multimedia capabilities, and expandability add further value, making each games console a central part of your entertainment system."]', unixepoch(), unixepoch()),
('consoles', 3, 'Video Games Console: The Ultimate Entertainment Hub', '["A video games console combines gaming performance with multimedia functionality, allowing you to enjoy games, movies, music, and more from a single device. Rouge Technologies'' video games consoles offer high-speed processors, advanced graphics, and seamless online connectivity for an all-encompassing entertainment experience. With access to exclusive titles and downloadable content, a video games console keeps your collection fresh and exciting.","Ideal for both solo and social gaming, these consoles provide ergonomic controllers, intuitive menus, and extensive support for accessories and peripherals. Whether you are setting up a dedicated gaming room or integrating a console into your living space, a video games console delivers unmatched entertainment and convenience.","From a console for games to versatile games consoles and high-performance video games consoles, Rouge Technologies provides everything needed to elevate your gaming experience. Each product is selected for reliability, quality, and performance, ensuring a seamless and enjoyable gaming experience for every user."]', unixepoch(), unixepoch()),
('pc-gaming', 0, NULL, '["Experience next-level performance with Rouge Technologies'' range of PC gaming products. Whether you are looking for gaming laptops, gaming desktops, or high-quality gaming monitors, our collection is designed to provide immersive visuals, fast processing, and unmatched reliability. Every product ensures a superior gaming experience for casual players, competitive gamers, and content creators alike."]', unixepoch(), unixepoch()),
('pc-gaming', 1, 'Gaming Laptops: Power and Portability', '["Gaming laptops combine high-performance hardware with portability, allowing you to game anywhere without compromising on speed or graphics. Rouge Technologies offers gaming laptops equipped with powerful processors, dedicated graphics cards, and high-refresh-rate displays to ensure smooth and responsive gameplay. Whether tackling fast-paced action titles, exploring expansive RPG worlds, or streaming content, a gaming laptop delivers the versatility and performance you need.","With customizable settings, cooling systems, and ergonomic designs, gaming laptops provide comfort and durability for long gaming sessions. These laptops also support the latest software and peripherals, making them an ideal choice for both professional gamers and enthusiasts seeking mobility without sacrificing power."]', unixepoch(), unixepoch());

-- Chunk 22 complete
