PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('chargers', 1, 'Buy iPhone Chargers: Reliable Power for Apple Devices', '["When you buy iPhone chargers from Rouge Technologies, you gain access to high-quality products designed for fast, efficient, and safe charging. Compatible with all recent iPhone models, these chargers ensure your device maintains optimal battery performance while protecting against overcharging and overheating. Whether at home, in the office, or on the move, our iPhone chargers provide a dependable solution for powering your device.","Rouge Technologies offers a variety of iPhone chargers, including wall adapters, car chargers, and USB-C options. Each product is carefully selected to guarantee safety, durability, and long-lasting performance, making it easy to keep your iPhone fully charged at all times."]', unixepoch(), unixepoch()),
('chargers', 2, 'Buy Laptop Chargers: Power for Work and Play', '["Laptop chargers are essential for professionals, students, and gamers who rely on their devices for work, study, or entertainment. When you buy laptop chargers from Rouge Technologies, you can choose from a wide range of models compatible with popular laptop brands and specifications. Our chargers provide reliable, consistent power to keep your laptop running efficiently without interruptions.","Whether you need a replacement charger or an additional one for travel or the office, Rouge Technologies ensures that every laptop charger delivers safety, compatibility, and long-term reliability. Fast-charging options and durable designs make it simple to stay productive and connected wherever you are."]', unixepoch(), unixepoch()),
('chargers', 3, 'Buy Portable Chargers: Power On the Go', '["Portable chargers, or power banks, are perfect for keeping your devices powered when away from traditional outlets. By choosing to buy portable chargers from Rouge Technologies, you gain access to high-capacity, reliable devices that ensure your smartphones, tablets, and other electronics stay charged throughout the day. Portable chargers are ideal for travel, commuting, or outdoor activities, providing peace of mind that your devices will never run out of power unexpectedly.","Our portable chargers feature fast charging capabilities, multiple ports, and compact designs, making it easy to carry and use them anywhere. Whether you need to charge an iPhone, laptop, or other device, portable chargers from Rouge Technologies deliver convenience, reliability, and efficiency for all your charging needs.","From buying iPhone chargers and laptop chargers to portable chargers, Rouge Technologies offers high-quality solutions that keep your devices powered, protected, and ready for use. Each charger is designed with safety, performance, and convenience in mind, ensuring a seamless charging experience for all your electronics."]', unixepoch(), unixepoch()),
('other-mobile-phones-wearable-tech', 0, NULL, '["Upgrade your mobile and wearable technology setup with essential accessories and innovative devices available at Rouge Technologies. Whether you are looking for a smart ring, iPhone accessories, or a USB C charging cable, our range provides reliable, high-quality solutions that enhance your mobile experience. Each product is designed to improve functionality, convenience, and connectivity for everyday use."]', unixepoch(), unixepoch()),
('other-mobile-phones-wearable-tech', 1, 'Smart Ring: Compact Technology on Your Finger', '["A smart ring offers an innovative way to stay connected, monitor health, and manage notifications without needing to constantly check your phone. Rouge Technologies'' selection of smart rings provides features such as activity tracking, sleep monitoring, heart rate detection, and discreet notification alerts. Designed for comfort and durability, a smart ring is an excellent choice for anyone looking to integrate technology seamlessly into daily life.","Whether you are a fitness enthusiast, a busy professional, or someone seeking convenient access to notifications, a smart ring allows you to keep track of essential data and stay connected while keeping your hands free. With sleek designs and advanced functionality, smart rings combine style with practicality."]', unixepoch(), unixepoch());

-- Chunk 14 complete
