PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('tvs', 0, NULL, '["Upgrade your home entertainment setup with high-quality TVs from Rouge Technologies. Whether you are looking for smart TVs, TV wall brackets, or want to buy televisions, our range offers reliable, stylish, and high-performance options to enhance your viewing experience. From immersive picture quality to convenient mounting solutions, our products are designed to deliver exceptional value for your home."]', unixepoch(), unixepoch()),
('tvs', 1, 'Smart TVs: Streamlined Entertainment at Your Fingertips', '["Smart TVs combine exceptional display quality with built-in connectivity, allowing you to stream your favourite shows, movies, and apps with ease. Rouge Technologies offers a wide range of smart TVs featuring high-definition displays, advanced colour accuracy, and responsive interfaces. Whether you are watching sports, streaming content, or gaming, a smart TV provides an engaging and versatile viewing experience for the whole family.","With access to popular streaming platforms and intuitive controls, smart TVs make it simple to enjoy entertainment without the need for additional devices. Advanced features such as voice control, app integration, and multiple connectivity options ensure a seamless and enjoyable experience in every room."]', unixepoch(), unixepoch()),
('tvs', 2, 'TV Wall Brackets: Secure and Space-Saving Mounting Solutions', '["TV wall brackets provide a safe and convenient way to mount your television while maximising space and improving viewing angles. Rouge Technologies offers a selection of sturdy and adjustable TV wall brackets suitable for a wide range of TV sizes and styles. These brackets allow you to position your television at the perfect height and angle for comfort, reducing glare and enhancing the overall viewing experience.","Easy installation and durable construction make our TV wall brackets a practical choice for home entertainment setups. By mounting your TV securely, you not only create a cleaner, clutter-free environment but also protect your investment for long-term use."]', unixepoch(), unixepoch()),
('tvs', 3, 'Buy Televisions: Choose the Right TV for Your Home', '["When you want to buy televisions, Rouge Technologies provides a variety of options to suit different preferences, room sizes, and budgets. From smart TVs to standard HD models, our collection delivers excellent picture quality, vibrant colours, and reliable performance. Whether you are upgrading your living room, bedroom, or office, buying a television from Rouge Technologies ensures you get a product that meets your needs and exceeds your expectations.","Each television is selected for quality, performance, and longevity, giving you peace of mind and an exceptional viewing experience. With options for different sizes, features, and price ranges, buying a television has never been easier or more satisfying.","From smart TVs and TV wall brackets to buying televisions, Rouge Technologies offers a complete range of products to enhance your home entertainment. Every product is designed to deliver exceptional performance, convenience, and style, helping you create the ultimate viewing experience in any space."]', unixepoch(), unixepoch()),
('projectors', 0, NULL, '["Transform your living room into a cinematic experience with high-quality projectors from Rouge Technologies. Whether you are searching for a home projector, a home cinema projector, or a projector for television, our selection provides exceptional performance, vibrant visuals, and reliable functionality. Each product is designed to enhance your viewing experience, whether for movies, sports, or gaming."]', unixepoch(), unixepoch());

-- Chunk 17 complete
