PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('other-smart-home', 1, 'Smart Home Automation Devices for Seamless Integration', '["Smart home automation devices allow you to control lighting, climate, security, and entertainment systems from a single interface. By setting schedules, triggers, and automated routines, these devices ensure that your home operates efficiently and responds to your lifestyle. With advanced smart home automation devices, you can monitor and control your home remotely, optimize energy usage, and increase overall convenience, making everyday living smoother and more enjoyable.","Rouge Technologies offers a range of smart home automation devices that are easy to install and compatible with popular platforms. From smart thermostats and automated lighting to connected security cameras, these devices integrate seamlessly to create a responsive and intuitive home environment that adapts to your needs."]', unixepoch(), unixepoch()),
('other-smart-home', 2, 'Smart Home Gadgets for Everyday Convenience', '["Smart home gadgets enhance everyday life by providing control, automation, and connectivity. Devices such as voice-activated assistants, smart plugs, connected sensors, and intelligent appliances allow you to manage your home effortlessly. Whether adjusting lighting, controlling entertainment systems, or monitoring security, smart home gadgets from Rouge Technologies provide convenience and efficiency, making your home more comfortable and functional.","High-quality smart home gadgets are designed to be user-friendly, reliable, and compatible with a wide range of devices. By investing in these gadgets, you can simplify routines, save time, and enjoy the benefits of a modern connected lifestyle."]', unixepoch(), unixepoch()),
('other-smart-home', 3, 'Smart Home Products for a Modern Living Experience', '["Smart home products enable a holistic approach to home management, combining technology, convenience, and security. From energy-efficient devices to advanced monitoring systems, these products ensure that every aspect of your home operates smoothly and efficiently. Rouge Technologies offers smart home products that are durable, easy to use, and designed to enhance your daily life.","By incorporating smart home products into your living space, you can enjoy improved energy management, enhanced security, and streamlined control over household systems. Whether you are just starting to explore home automation or expanding an existing setup, Rouge Technologies provides smart home products that are reliable, innovative, and tailored to your lifestyle. Investing in these products ensures a connected, efficient, and modern home that adapts to your needs."]', unixepoch(), unixepoch()),
('mobile-phones-wearable-tech', 0, NULL, '["Staying connected and up-to-date with the latest technology is effortless when you choose the right devices. Whether you want to buy mobile phones, explore mobile phones for sale, or buy smart watches, Rouge Technologies offers a wide selection of high-quality products to meet every lifestyle and requirement. From everyday communication to fitness tracking and smart functionality, our devices are designed to enhance your daily life."]', unixepoch(), unixepoch()),
('mobile-phones-wearable-tech', 1, 'Buy Mobile Phones for Every Need', '["Choosing to buy mobile phones from Rouge Technologies ensures you get devices with the latest features, reliable performance, and stylish designs. Whether you need a smartphone for work, study, gaming, or social connectivity, our range of mobile phones caters to every requirement. High-resolution cameras, long-lasting batteries, and powerful processors provide an exceptional user experience, while durable construction ensures your device performs reliably over time.","With options suitable for different budgets and preferences, buying mobile phones allows you to select a device that perfectly fits your lifestyle. Advanced operating systems and seamless connectivity features ensure that every phone you buy from Rouge Technologies keeps you connected, productive, and entertained wherever you are."]', unixepoch(), unixepoch());

-- Chunk 10 complete
