PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('home-automation', 2, 'Smart Home Gadgets for Everyday Convenience', '["Smart home gadgets bring functionality and innovation to everyday life. Devices such as voice-controlled assistants, smart plugs, connected cameras, and motion sensors allow homeowners to simplify daily routines and stay in control of their homes. These gadgets make it easy to monitor, manage, and customize your environment while keeping your household safe and comfortable. Whether you''re adjusting lighting, checking on family members, or controlling entertainment systems, smart home gadgets provide seamless, hands-free convenience.","With high-quality smart home gadgets from Rouge Technologies, you can enjoy reliable performance, intuitive controls, and compatibility with a variety of devices. These gadgets are designed to enhance productivity, simplify tasks, and create a connected home ecosystem that adapts to your lifestyle effortlessly."]', unixepoch(), unixepoch()),
('home-automation', 3, 'Smart Home Products for Enhanced Living', '["Investing in smart home products allows you to create a home that is efficient, secure, and responsive. From energy-saving appliances to advanced security systems, these products deliver value and convenience while supporting modern living standards. Smart home products such as automated lighting, programmable thermostats, and connected entertainment devices improve daily life by providing control, comfort, and peace of mind.","Rouge Technologies offers a wide range of smart home products that are reliable, user-friendly, and scalable. Whether you are just beginning to explore home automation or looking to expand an existing system, these products help you create an integrated environment where technology works seamlessly to enhance your living space. By choosing smart home products from Rouge Technologies, you ensure that your home remains connected, efficient, and adaptable to your needs, making every day more comfortable, convenient, and enjoyable."]', unixepoch(), unixepoch()),
('wifi-routers-networking', 0, NULL, '["Reliable internet connectivity is essential for work, study, entertainment, and smart home integration. Choosing the right wifi router for home ensures seamless connections, fast speeds, and stable performance across all devices. Rouge Technologies offers a comprehensive range of home wifi routers and wireless routers designed to meet the needs of modern households, whether for casual browsing, gaming, streaming, or smart home management."]', unixepoch(), unixepoch()),
('wifi-routers-networking', 1, 'Wifi Router for Home: Ensuring Fast and Stable Connectivity', '["A wifi router for home is the backbone of any connected household. High-quality routers provide consistent coverage, reduce signal dropouts, and support multiple devices simultaneously. By selecting the right wifi router for home from Rouge Technologies, you can ensure uninterrupted internet access for work, video calls, online learning, and entertainment. Advanced features such as dual-band or tri-band networks, MU-MIMO technology, and QoS settings allow you to prioritise devices and optimize performance for demanding applications like gaming or streaming.","Rouge Technologies'' selection of wifi routers for home includes options suitable for small apartments, larger houses, and even multi-floor properties. Each router is designed to deliver reliable connectivity, ensuring every corner of your home has strong, stable wifi coverage. With easy setup and compatibility with smart devices, these routers simplify network management while providing top-tier performance."]', unixepoch(), unixepoch()),
('wifi-routers-networking', 2, 'Home Wifi Routers for Every Need', '["Home wifi routers are essential for creating a connected and efficient network environment. Whether you need a router for basic internet browsing, high-speed streaming, or online gaming, Rouge Technologies offers a wide selection of routers to suit every requirement. These home wifi routers are engineered to provide strong signals, secure connections, and advanced network management options, making it easy to control and monitor your network.","By choosing home wifi routers from Rouge Technologies, you gain access to devices with enhanced coverage, faster data transfer rates, and robust security features. Features like parental controls, guest networks, and VPN support help keep your network safe and adaptable to the needs of every household member."]', unixepoch(), unixepoch());

-- Chunk 7 complete
