PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('other-computers-tablets', 0, NULL, '["Enhancing your computing setup begins with the right computer accessories. Whether you use a desktop, laptop, or tablet, having high-quality accessories can significantly improve productivity, comfort, and efficiency. Rouge Technologies offers a wide selection of personal computer accessories and laptop computer accessories to suit every need, from ergonomic peripherals to protective solutions and connectivity tools."]', unixepoch(), unixepoch()),
('other-computers-tablets', 1, 'Computer Accessories for Everyday Use', '["Computer accessories are essential for optimizing your workspace and ensuring smooth operation. Keyboards, mice, monitors, and storage devices are just a few examples of items that can enhance your desktop experience. By investing in reliable computer accessories, you can improve efficiency, reduce strain during extended use, and make your system easier to navigate. Whether working, studying, or gaming, the right accessories help you get the most out of your devices.","Rouge Technologies provides computer accessories that are compatible with a wide range of systems, ensuring seamless integration and ease of use. From high-precision input devices to ergonomic setups, these accessories are designed to make everyday tasks more comfortable and productive, giving users the tools they need to stay focused and efficient."]', unixepoch(), unixepoch()),
('other-computers-tablets', 2, 'Personal Computer Accessories for Enhanced Productivity', '["Personal computer accessories offer functionality and convenience for both home and office environments. Items such as external storage drives, USB hubs, and multi-port adapters make managing files and connecting multiple devices simple and efficient. High-quality personal computer accessories help streamline workflows, whether for professional tasks, creative projects, or daily computing needs.","Investing in personal computer accessories allows users to customize their setup to fit specific requirements. Ergonomic keyboards and mice, monitor stands, and cable management solutions improve comfort and organization, while functional accessories like external drives and docking stations provide practical support for productivity. With the right personal computer accessories, users can optimize their systems and work more effectively."]', unixepoch(), unixepoch()),
('other-computers-tablets', 3, 'Laptop Computer Accessories for Mobility and Performance', '["Laptop computer accessories are designed to enhance portability, protect your device, and extend its capabilities. Cooling pads, protective cases, portable stands, and external keyboards allow users to work comfortably on the go while maintaining performance. These accessories are essential for students, professionals, and anyone who relies on their laptop for daily tasks.","Rouge Technologies offers a wide variety of laptop computer accessories that ensure durability, compatibility, and convenience. From charging solutions and external storage to ergonomic enhancements and protective gear, each accessory is selected to maximize your laptop''s efficiency and usability. By equipping your laptop with the right accessories, you can work, create, and play without compromise, making your computing experience more versatile and enjoyable.","Whether you are upgrading your desktop, enhancing a personal computer, or outfitting a laptop for mobility, Rouge Technologies provides computer accessories, personal computer accessories, and laptop computer accessories that combine quality, functionality, and reliability. Investing in the right accessories ensures a seamless, efficient, and comfortable computing experience for every user."]', unixepoch(), unixepoch()),
('smart-home', 0, NULL, '["Creating a connected and efficient living space starts with choosing the right home smart devices. Whether you are looking to enhance convenience, improve security, or increase energy efficiency, Rouge Technologies offers a comprehensive selection of smart home devices and smart home automation devices to suit every household. Integrating these devices allows you to manage your home more effectively, providing comfort and peace of mind."]', unixepoch(), unixepoch());

-- Chunk 5 complete
