PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('speakers', 2, 'Portable Speakers: Sound on the Move', '["Portable speakers are perfect for users who want great sound wherever they go. Rouge Technologies'' portable speakers are lightweight, compact, and designed for travel, picnics, or outdoor events. Despite their size, they deliver clear audio, impressive bass, and durable performance that can handle different environments.","With features such as splash resistance, long-lasting battery life, and easy connectivity, portable speakers ensure that you can take your music everywhere. They are ideal for casual listening, parties, or spontaneous adventures, providing reliable and enjoyable sound on the move."]', unixepoch(), unixepoch()),
('speakers', 3, 'Wireless Speakers: Seamless Home and Outdoor Audio', '["Wireless speakers offer freedom from cables while delivering high-fidelity sound throughout your space. Our wireless speakers from Rouge Technologies are perfect for creating an immersive audio experience in your home, office, or garden. With multi-room connectivity, intuitive controls, and modern designs, wireless speakers integrate effortlessly into your lifestyle.","Whether you are streaming music, watching movies, or hosting events, wireless speakers provide consistent and high-quality sound performance. They are easy to set up, flexible in placement, and offer the convenience of managing your audio system without the restrictions of wires.","From Bluetooth speakers and portable speakers to wireless speakers, Rouge Technologies offers a comprehensive selection of high-performance audio solutions. Every product is designed to deliver exceptional sound quality, portability, and convenience, ensuring a superior listening experience for every environment and occasion."]', unixepoch(), unixepoch()),
('other-sound-vision', 0, NULL, '["Enhance your entertainment setup with premium sound and vision solutions from Rouge Technologies. Whether you are looking for audio accessories and cables, TV wall brackets, or a range of cables and accessories, our selection ensures high-quality performance, convenience, and reliability. Each product is designed to help you optimise your home audio-visual experience with ease and efficiency."]', unixepoch(), unixepoch()),
('other-sound-vision', 1, 'Audio Accessories and Cables: Reliable Connections for Perfect Sound', '["Audio accessories and cables are essential for achieving the best sound from your devices. Rouge Technologies offers a wide range of high-quality audio accessories and cables designed to deliver clear, uninterrupted audio for speakers, headphones, and home theatre systems. From HDMI and optical cables to specialised audio connectors, these products ensure your devices communicate seamlessly, maintaining the integrity of your sound setup.","Whether you are setting up a home cinema, connecting a stereo system, or enhancing your gaming setup, audio accessories and cables provide the foundation for superior performance. Durable construction and high-quality materials help prevent signal loss, interference, and wear, ensuring reliable connections for years to come."]', unixepoch(), unixepoch()),
('other-sound-vision', 2, 'TV Wall Brackets: Secure and Space-Saving Mounting', '["TV wall brackets offer a practical solution for mounting your television securely while optimising space and improving viewing angles. Rouge Technologies provides a variety of TV wall brackets suitable for different sizes and types of televisions. These brackets allow you to position your TV at the perfect height and angle for maximum comfort and enjoyment.","Our TV wall brackets are built for strength and durability, making it simple to mount your TV safely on any wall. Adjustable and easy to install, these brackets enhance your home entertainment setup while keeping cables organised and out of the way, contributing to a clean and professional look."]', unixepoch(), unixepoch());

-- Chunk 19 complete
