PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('other-digital-cameras-photography', 0, NULL, '["Take your photography to the next level with a wide range of camera accessories, camera equipment, and digital camera equipment available at Rouge Technologies. Whether you are a hobbyist or a professional, having the right accessories and equipment ensures that you capture every shot with precision, quality, and ease. From tripods and memory cards to lighting and stabilisers, our products are designed to enhance your photography experience."]', unixepoch(), unixepoch()),
('other-digital-cameras-photography', 1, 'Camera Accessories: Essential Tools for Every Photographer', '["Camera accessories are crucial for improving the functionality and versatility of your camera setup. At Rouge Technologies, we offer a variety of camera accessories including lens filters, camera bags, battery packs, and cleaning kits. These accessories help protect your gear, maintain optimal performance, and allow you to capture better images under different conditions. Investing in high-quality camera accessories ensures your equipment stays in top condition and that your photography workflow remains smooth and efficient.","Whether you need a sturdy tripod for stable shots, external flashes for better lighting, or remote shutter releases for creative perspectives, camera accessories can dramatically enhance the quality and creativity of your work. Each accessory is designed to complement your existing gear, making photography more enjoyable and professional."]', unixepoch(), unixepoch()),
('other-digital-cameras-photography', 2, 'Camera Equipment: Build a Complete Photography Setup', '["Camera equipment includes everything you need to create a fully functional photography studio or mobile shooting setup. Rouge Technologies provides camera equipment such as stabilisers, gimbals, lens hoods, and advanced lighting kits to ensure you have the right tools for every scenario. High-quality camera equipment allows photographers to achieve sharper images, consistent exposure, and more control over their shots, whether shooting indoors, outdoors, or in challenging environments.","With the right camera equipment, photographers can experiment with angles, perspectives, and lighting setups to achieve professional-level results. Each piece of equipment is selected for its durability, reliability, and ease of use, making it suitable for both beginners and seasoned photographers looking to expand their capabilities."]', unixepoch(), unixepoch()),
('other-digital-cameras-photography', 3, 'Digital Camera Equipment: Optimise Performance and Versatility', '["Digital camera equipment is specifically designed to support modern digital photography, offering precision, convenience, and enhanced performance. From high-capacity memory cards to advanced battery systems and lens adapters, our digital camera equipment ensures that your camera performs at its best in any shooting situation. Rouge Technologies stocks a wide selection of digital camera equipment that caters to DSLR, mirrorless, and compact cameras alike, giving you the tools to capture stunning images effortlessly.","Investing in digital camera equipment allows photographers to extend the capabilities of their cameras, improve image quality, and adapt to various shooting conditions. Whether capturing high-speed action, detailed macro shots, or expansive landscapes, digital camera equipment helps you achieve professional results and elevate your photography.","Explore Rouge Technologies'' range of camera accessories, camera equipment, and digital camera equipment to create a versatile, high-performance photography setup that meets all your creative needs."]', unixepoch(), unixepoch()),
('other-products', 0, NULL, '["Discover a diverse range of products at Rouge Technologies, including makeup products, skincare products, and business tech products. Whether you are looking to enhance your beauty routine or upgrade your office setup, our carefully curated selection ensures quality, effectiveness, and reliability. Each product is designed to meet the needs of modern consumers who value performance, convenience, and innovation."]', unixepoch(), unixepoch());

-- Chunk 29 complete
