PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('camcorders', 3, '4K Video Camera: Ultra-High Definition Recording', '["A 4K video camera delivers the highest resolution available for consumer and professional video recording. Rouge Technologies offers 4K video cameras that provide ultra-sharp imagery, vibrant colours, and advanced image processing, ensuring every video is cinematic in quality. Whether filming landscapes, sports, or personal projects, a 4K video camera ensures exceptional detail and realism in every frame.","4K video cameras also include features such as high frame rate recording, electronic stabilisation, and versatile connectivity options, allowing for seamless editing and sharing. By choosing a 4K video camera from Rouge Technologies, videographers can create content that stands out with superior clarity and immersive visual impact.","From digital video cameras and digital video camcorders to 4K video cameras, Rouge Technologies provides the equipment needed to capture, create, and share high-quality video content. Each product is designed to help users achieve professional results, whether for personal enjoyment or creative projects."]', unixepoch(), unixepoch()),
('lenses', 0, NULL, '["Enhance your photography with a wide selection of lenses at Rouge Technologies. Whether you are looking for camera lenses, DSLR camera lenses, or Canon camera lenses, our collection is designed to meet the needs of both amateur photographers and professionals. Each lens delivers sharp images, vibrant colours, and precise focus to help you capture every moment with clarity and creativity."]', unixepoch(), unixepoch()),
('lenses', 1, 'Camera Lenses: Versatility and Precision', '["Camera lenses are essential for capturing a variety of scenes, from sweeping landscapes to intimate close-ups. Rouge Technologies offers camera lenses that cover wide-angle, telephoto, and macro options, allowing photographers to expand their creative possibilities. Each lens is engineered to provide sharp detail, accurate colour reproduction, and excellent low-light performance, ensuring high-quality results in any environment.","Whether you are photographing fast-moving subjects, intricate textures, or panoramic vistas, the right camera lens enhances your ability to frame and capture every shot perfectly. Lightweight and durable designs also make these lenses easy to carry and ideal for on-the-go photography."]', unixepoch(), unixepoch()),
('lenses', 2, 'DSLR Camera Lenses: Professional Flexibility', '["DSLR camera lenses provide the versatility and precision needed for professional photography. Rouge Technologies stocks a variety of DSLR camera lenses, including prime lenses, zoom lenses, and specialty lenses for portrait, landscape, and wildlife photography. These lenses offer superior optical performance, fast autofocus, and reliable construction, allowing photographers to achieve professional-quality results in any setting.","With DSLR camera lenses, you can control depth of field, focal length, and perspective to produce creative and impactful images. Each lens is carefully designed to complement DSLR camera bodies, providing seamless integration and consistent performance for demanding photographic projects."]', unixepoch(), unixepoch()),
('lenses', 3, 'Canon Camera Lenses: Quality and Reliability', '["Canon camera lenses are renowned for their exceptional image quality and robust performance. Rouge Technologies offers a comprehensive range of Canon camera lenses, compatible with a variety of Canon DSLR and mirrorless cameras. From wide-angle lenses for sweeping landscapes to telephoto lenses for capturing distant subjects, Canon camera lenses deliver sharp, detailed, and vibrant images.","Whether you are a professional photographer or an enthusiastic hobbyist, Canon camera lenses provide the reliability, precision, and optical excellence needed to capture stunning photographs. Investing in Canon camera lenses ensures long-lasting performance and consistent results, helping you elevate your photography to the next level.","Explore Rouge Technologies'' range of camera lenses, DSLR camera lenses, and Canon camera lenses to expand your creative potential and achieve outstanding photographic results. Each lens is carefully selected to deliver quality, versatility, and exceptional image performance."]', unixepoch(), unixepoch());

-- Chunk 28 complete
