PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('digital-cameras', 1, 'Digital Cameras: Capture Every Moment', '["Digital cameras offer portability, advanced features, and excellent image quality, making them ideal for both casual and professional photography. Rouge Technologies provides a variety of digital cameras, including compact models for everyday use and advanced cameras for serious photographers. With features such as high-resolution sensors, fast autofocus, and intuitive controls, digital cameras make it easier to capture sharp and vibrant images in any setting.","Whether photographing landscapes, portraits, or fast-moving subjects, a digital camera ensures that every shot is accurately captured. Ergonomic designs, user-friendly menus, and advanced settings allow you to focus on creativity while achieving professional results."]', unixepoch(), unixepoch()),
('digital-cameras', 2, 'DSLR Camera: Professional-Grade Photography', '["A DSLR camera offers the power and flexibility needed for professional photography. Rouge Technologies stocks a wide range of DSLR cameras that provide exceptional image quality, manual control over exposure, and the ability to change lenses for different shooting scenarios. With a DSLR camera, you can capture everything from dramatic landscapes to detailed close-ups with precision and clarity.","DSLR cameras are also equipped with advanced autofocus systems, rapid shooting capabilities, and superior low-light performance, making them ideal for photographers who demand the highest standards. Whether you are shooting stills or recording high-definition video, a DSLR camera delivers the tools necessary for professional results."]', unixepoch(), unixepoch()),
('digital-cameras', 3, 'DSLR Digital Cameras: Versatile and Reliable', '["DSLR digital cameras combine the power of digital imaging with the flexibility of interchangeable lenses. Rouge Technologies'' selection of DSLR digital cameras allows you to tailor your setup to specific photography needs, whether it''s portraits, sports, wildlife, or studio work. High-resolution sensors, precise focusing systems, and robust build quality ensure consistent performance in any environment.","With DSLR digital cameras, photographers gain complete creative control, enabling adjustments to shutter speed, aperture, and ISO for optimal results. These cameras are designed for both enthusiasts and professionals, providing the versatility and durability needed for long-term use.","Whether you are exploring digital cameras, investing in a DSLR camera, or upgrading to DSLR digital cameras, Rouge Technologies offers products that combine cutting-edge technology with reliability and performance. Each camera is carefully selected to help you capture stunning images and bring your creative vision to life."]', unixepoch(), unixepoch()),
('drones', 0, NULL, '["Experience the thrill of aerial photography and videography with a range of drones at Rouge Technologies. Whether you are searching for drones with cameras, DJI drones UK, or want to buy drones UK, our selection is designed to meet the needs of both hobbyists and professional filmmakers. Each drone combines advanced technology, reliability, and ease of use to help you capture stunning aerial footage."]', unixepoch(), unixepoch()),
('drones', 1, 'Drones with Cameras: Capture Unique Perspectives', '["Drones with cameras allow you to explore new angles and create breathtaking visuals from the sky. Rouge Technologies offers drones equipped with high-resolution cameras, stabilisation systems, and intelligent flight modes, making it easy to capture sharp and smooth footage. Whether photographing landscapes, recording events, or producing cinematic videos, drones with cameras provide unparalleled versatility and creative freedom.","These drones feature intuitive controls, automated flight paths, and long battery life, ensuring that every flight is both safe and productive. By investing in a drone with a camera, you can take your photography and videography to the next level while enjoying the excitement of flying a high-performance device."]', unixepoch(), unixepoch());

-- Chunk 26 complete
