PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('mobile-phones-wearable-tech', 2, 'Mobile Phones for Sale: Wide Range and Easy Access', '["Our collection of mobile phones for sale offers an extensive variety of devices, from the latest flagship models to reliable everyday smartphones. Whether you''re upgrading your current phone or purchasing your first device, Rouge Technologies provides mobile phones for sale that combine performance, innovation, and affordability. Each device undergoes careful selection to ensure quality, functionality, and user satisfaction.","Mobile phones for sale at Rouge Technologies come with advanced features such as high-speed processors, large storage capacities, and superior display technology. These devices are ideal for multitasking, streaming, gaming, and staying connected through calls, messaging, and social media, ensuring that you always have a reliable device in hand."]', unixepoch(), unixepoch()),
('mobile-phones-wearable-tech', 3, 'Buy Smart Watch for Enhanced Convenience', '["Smart watches are the perfect companion for mobile devices, providing notifications, fitness tracking, and hands-free functionality. When you buy smart watches from Rouge Technologies, you gain access to wearable technology designed to keep you informed, active, and connected. Whether monitoring health metrics, tracking workouts, or receiving alerts, smart watches enhance your lifestyle with convenience and style.","Rouge Technologies offers smart watches that are compatible with a wide range of mobile phones, ensuring seamless integration and easy management of your digital life. By investing in a smart watch alongside your mobile phone, you can enjoy a fully connected and efficient experience, whether at work, at home, or on the move.","Whether you choose to buy mobile phones, explore mobile phones for sale, or buy smart watches, Rouge Technologies provides reliable, high-quality devices that enhance connectivity, productivity, and daily convenience. Each product is designed to deliver long-lasting performance, modern features, and an enjoyable user experience."]', unixepoch(), unixepoch()),
('apple-iphone', 0, NULL, '["Experience cutting-edge technology and sleek design with the latest Apple iPhones. Whether you are looking to explore an iPhone for sale, buy iPhone models for personal or professional use, or shop iPhone devices online, Rouge Technologies offers a premium selection that combines performance, style, and innovation. Each iPhone is designed to deliver a seamless user experience, ensuring that you stay connected, productive, and entertained."]', unixepoch(), unixepoch()),
('apple-iphone', 1, 'iPhone for Sale: Wide Selection and Quality Assurance', '["Our collection of iPhones for sale includes the newest releases as well as reliable models suitable for various needs and budgets. Each device is carefully tested for quality and performance, ensuring you receive a smartphone that operates smoothly and efficiently. iPhones for sale at Rouge Technologies offer advanced features such as high-resolution cameras, powerful processors, and long-lasting batteries, making them ideal for photography, multitasking, gaming, and everyday communication.","Rouge Technologies makes it easy to browse and select the perfect iPhone for sale, whether you are upgrading your current device or purchasing your first Apple smartphone. Every iPhone combines elegant design with durable construction, providing a device that performs reliably for years to come."]', unixepoch(), unixepoch()),
('apple-iphone', 2, 'Buy iPhone: Seamless Shopping Experience', '["When you buy an iPhone from Rouge Technologies, you gain access to trusted products backed by expert advice and support. Our range of iPhones ensures that you can find the right model to suit your lifestyle, whether you need a high-performance device for work, a versatile phone for everyday use, or a premium model for entertainment and creative projects. Buying an iPhone guarantees you a device that is fully compatible with Apple services and accessories, ensuring a seamless digital experience.","Rouge Technologies provides guidance on selecting the right iPhone, including storage options, colour choices, and connectivity features. By choosing to buy an iPhone from us, you can enjoy a reliable and satisfying purchase with confidence in the quality and authenticity of your device."]', unixepoch(), unixepoch());

-- Chunk 11 complete
