PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('other-products', 1, 'Makeup Products: Enhance Your Everyday Look', '["Rouge Technologies offers a wide selection of makeup products that help you achieve a flawless look for any occasion. From foundations and concealers to lipsticks and eyeshadows, each product is formulated for long-lasting wear, smooth application, and vibrant results. Our makeup products cater to all skin types and tones, ensuring that everyone can find the perfect match to enhance their natural beauty.","Whether you are a professional makeup artist or someone looking to elevate your daily routine, these makeup products provide the quality and performance needed for stunning results. Lightweight, easy to apply, and carefully tested, our makeup products help you feel confident and look your best every day."]', unixepoch(), unixepoch()),
('other-products', 2, 'Skincare Products: Nourish and Protect Your Skin', '["High-quality skincare products are essential for maintaining healthy, radiant skin. Rouge Technologies provides a comprehensive range of skincare products, including moisturisers, cleansers, serums, and sunscreens. Each product is formulated to protect, hydrate, and rejuvenate your skin while addressing specific concerns such as dryness, sensitivity, or signs of aging.","Using effective skincare products ensures that your skin stays smooth, resilient, and glowing. Whether you are establishing a daily skincare routine or seeking advanced solutions for targeted issues, our skincare products are designed to support long-term skin health and enhance your natural appearance."]', unixepoch(), unixepoch()),
('other-products', 3, 'Business Tech Products: Equip Your Workspace', '["Rouge Technologies also offers a selection of business tech products to enhance productivity and efficiency in professional environments. From laptops and monitors to printers and networking devices, our business tech products are designed to deliver reliability, performance, and ease of use. These products help streamline daily operations, improve workflow, and ensure that your office is equipped with the tools needed to succeed.","Whether setting up a home office, upgrading corporate equipment, or seeking specialised technology for specific tasks, our business tech products provide the versatility and quality required to meet modern business demands. Each product is carefully selected to ensure durability, compatibility, and long-term value, helping you maximise productivity and achieve your goals.","Explore Rouge Technologies'' range of makeup products, skincare products, and business tech products to enhance your personal care routine, professional workspace, and everyday life with high-quality, reliable, and effective solutions."]', unixepoch(), unixepoch()),
('health-and-beauty', 0, NULL, '["Elevate your personal care routine with a premium selection of makeup products, skincare products, and womens makeup available at Rouge Technologies. Our carefully curated collection ensures that every item combines quality, performance, and convenience, helping you look and feel your best every day. Whether you are enhancing your natural beauty or experimenting with new looks, our health and beauty range offers something for everyone."]', unixepoch(), unixepoch()),
('health-and-beauty', 1, 'Makeup Products: Enhance Your Look', '["Rouge Technologies provides a diverse range of makeup products designed to suit every skin type and tone. From foundations and concealers to lipsticks, eyeshadows, and blushes, each product is formulated to deliver smooth application, vibrant colours, and long-lasting wear. Our makeup products are ideal for everyday use, special occasions, or professional makeup artistry, allowing you to express your style with confidence.","Whether you are creating a subtle daytime look or a bold evening statement, these makeup products help you achieve flawless results. Lightweight and easy to apply, they provide the perfect combination of quality, durability, and comfort for all-day wear."]', unixepoch(), unixepoch());

-- Chunk 30 complete
