PRAGMA foreign_keys = ON;

INSERT INTO category_content (category_slug, section_order, subheading, paragraphs, created_at, updated_at) VALUES
('digital-cameras-photography', 0, NULL, '["Capture every moment in stunning detail with the latest digital cameras and photography equipment from Rouge Technologies. Whether you are searching for digital cameras, drones with cameras, or high-quality camera lenses, our collection is designed to help photographers and videographers of all levels achieve exceptional results. Each product combines cutting-edge technology, reliability, and durability to enhance your creative projects."]', unixepoch(), unixepoch()),
('digital-cameras-photography', 1, 'Digital Cameras: Precision and Versatility', '["Digital cameras offer the tools needed to take professional-quality photos and videos. Rouge Technologies provides a wide range of digital cameras, from compact models perfect for travel to advanced DSLR and mirrorless cameras for professional use. These cameras feature high-resolution sensors, fast autofocus, and intuitive controls to ensure every shot is sharp, vibrant, and accurately captured.","Whether you are photographing landscapes, portraits, or fast-moving action, a digital camera from Rouge Technologies delivers consistent performance and creative flexibility. Features such as interchangeable lenses, adjustable settings, and advanced image stabilization make it easier than ever to capture professional-level images and videos."]', unixepoch(), unixepoch()),
('digital-cameras-photography', 2, 'Drones with Cameras: Aerial Perspectives', '["Drones with cameras open up a new world of aerial photography and videography. Rouge Technologies offers drones equipped with high-definition cameras, stable flight systems, and smart features such as GPS tracking and automated flight paths. Whether capturing sweeping landscapes, real estate imagery, or action shots, drones with cameras provide unique perspectives that elevate your creative work.","Our drones are designed for both beginners and professionals, offering intuitive controls, long battery life, and reliable performance. By combining mobility with cutting-edge camera technology, drones with cameras make it possible to explore and capture scenes that were previously out of reach."]', unixepoch(), unixepoch()),
('digital-cameras-photography', 3, 'Camera Lenses: Expand Your Creative Possibilities', '["Camera lenses are essential for achieving the perfect shot. Rouge Technologies stocks a wide selection of camera lenses, from wide-angle lenses for expansive landscapes to telephoto lenses for detailed close-ups. High-quality camera lenses enhance sharpness, depth, and colour accuracy, giving your images a professional finish.","Whether you are shooting portraits, wildlife, or architectural photography, using the right camera lenses allows you to control focus, perspective, and lighting to create striking images. Rouge Technologies ensures each lens delivers exceptional performance, compatibility, and durability, supporting photographers in bringing their creative vision to life.","From digital cameras and drones with cameras to camera lenses, Rouge Technologies provides the equipment needed to capture, create, and share stunning visual content. Each product is chosen to support photographers and videographers in achieving clarity, precision, and artistic excellence."]', unixepoch(), unixepoch()),
('digital-cameras', 0, NULL, '["Take your photography to the next level with high-quality digital cameras from Rouge Technologies. Whether you are looking for digital cameras, a DSLR camera, or DSLR digital cameras, our range provides exceptional performance, reliability, and versatility for photographers of all skill levels. Each product is designed to help you capture stunning images with clarity and precision."]', unixepoch(), unixepoch());

-- Chunk 25 complete
